### ISSUE TITLE
Swamp Items

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#10]
Ensure all swamp items of the original game are implemented with their effects:
- [x] Life (increase player life by one)
- [x] PotionBig (restore all hearts)
- [x] PotionLittle (restore one heart)
- [x] Sword2 (set sword level to 2)
- [x] Talisment (increase player talisment by one, 100 talisments increase life by one)
