### ISSUE TITLE
Swamp Sceneries

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#11]
Ensure all swamp sceneries of the original game are implemented with their effects:
- [x] BeetleHorizontal (player can walk over)
- [x] BettleVertical (player can walk over)
- [x] Bird (hurt player, can be hit to walk over)
- [x] CarnivorousPlant (kill player)
- [x] Dragon (rise on player proximity and show its tongue where it is possible to move over)
- [x] Sheet (player can walk over & vertical move effect)
- [x] Spike1 & Spike2 (rise from ground & hit player)
- [x] TurningAuto (player can walk over when not turning)
- [x] TurningHit (always turning, can be hit to walk over)
- [x] Floater (floating over water, move down on over)
