### ISSUE TITLE
Swamp Foreground

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#13]
Ensure the water foreground is well implemented:
- [x] Water animation and movement
- [x] Distortion effect
- [x] Kill player at a defined height
- [x] Specific Raster color under water
