### ISSUE TITLE
Lava Foreground

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#159]
Ensure the lava foreground is well implemented:
- [x] Water animation and movement
- [x] No distortion effect
- [x] Kill player at a defined height
- [x] Specific Raster color under water
