### ISSUE TITLE
Dragonfly Boss

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#188]
* [x] Head tracking
* [x] Head laser attack
* [x] Body ground collision
* [x] Goblin throws
* [x] Neck hurt
* [x] Boss flickering on hurt
* [x] Death explode
