### ISSUE TITLE
Norka Foreground

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#198]
Ensure the lava foreground is well implemented:
- [x] Lava animation and movement
- [x] Kill player at a defined height
- [x] Specific Raster color under lava
