### ISSUE TITLE
Gameplay Control

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#66]
Cover all gameplay functions, with player control and interactions.
- [x] Movements
- [x] Gravity
- [x] Attacks
- [x] Slope reduce / increase speed
- [x] Steep force going down
- [x] Liana
- [x] Borders
- [x] Camera tracking with limits
- [x] Talisment / Health / Life / Sword
- [x] Starting, ending and checkpoints location
