### ISSUE TITLE
Swamp Monsters

### ISSUE THREAD

**Issue by DjThunder** [b3dgs/lionheart-remake#9]
Ensure all swamp monsters of the original game are implemented with their AI:
- [x] Bee (simple patrol)
- [x] Crawling (simple patrol & jump on border)
- [x] Dino (simple patrol, fall on border & slide on slopes)
- [x] Flower (point player & throws projectile)
- [x] Grasshoper (jump & throws Fly)
- [x] NestLittle (throws fly)
